include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    cascade_invocations: ignore
linter:
  rules:
    public_member_api_docs: false
    use_setters_to_change_properties: false
    avoid_positional_boolean_parameters: false
