// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8zm_qA8p9F5NVIN3sgqq3xBUP0P7GULY',
    appId: '1:430595920960:web:4510e919e3058fda0dfba5',
    messagingSenderId: '430595920960',
    projectId: 'hemo-gtkd',
    authDomain: 'hemo-gtkd.firebaseapp.com',
    storageBucket: 'hemo-gtkd.firebasestorage.app',
    measurementId: 'G-LVFJF79H21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9YwxX3GCK8RUubvaVRFWDnUPnFHx-v-I',
    appId: '1:430595920960:android:e5da05a0eba5d26f0dfba5',
    messagingSenderId: '430595920960',
    projectId: 'hemo-gtkd',
    storageBucket: 'hemo-gtkd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxZDQGLEG0azCUA78XSrFZzd0ZBHKZTyw',
    appId: '1:430595920960:ios:c15c6e4fcaff26a30dfba5',
    messagingSenderId: '430595920960',
    projectId: 'hemo-gtkd',
    storageBucket: 'hemo-gtkd.firebasestorage.app',
    iosClientId: '430595920960-ldu6p1ger8n3s7ld5frpuet4liori6v9.apps.googleusercontent.com',
    iosBundleId: 'com.gettoknowdavid.hemo',
  );

}